apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  project: default
  sources:
  - repoURL: 'https://harbor.starburstdata.net/chartrepo/starburstdata'
    chart: starburst-enterprise
    targetRevision: 413.0.0
    helm:
      valueFiles:
      - $values/sep-dev/sep-coordinator.yaml
  - repoURL: 'https://github.com/chrisstarburst/sep-argocd-example.git'
    targetRevision: HEAD
    ref: values
  destination:
    server: "https://821A657B9460A795146614E2F6C4C476.gr7.us-east-2.eks.amazonaws.com"
    namespace: dev  

